class ERROR_CODE(object):
    BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR"
    GATEWAY_ERROR = "GATEWAY_ERROR"
    SERVER_ERROR = "SERVER_ERROR"

    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"
    NOT_FOUND = "NOT_FOUND"
    INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR"
